=== uo294254/sew/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud, anchura, fecha, hora, vueltas, localidad, pais, patrocinador, referencias, fotos, videos, punto_origen, tramos, resultado, clasificacion)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidades CDATA #REQUIRED>

<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura unidades CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto archivo CDATA #REQUIRED>

<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video archivo CDATA #REQUIRED>

<!ELEMENT punto_origen (longitud_geo, latitud_geo, altitud_geo)>
<!ELEMENT longitud_geo (#PCDATA)>
<!ELEMENT latitud_geo (#PCDATA)>
<!ELEMENT altitud_geo (#PCDATA)>

<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, longitud_geo, latitud_geo, altitud_geo, sector)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ELEMENT sector (#PCDATA)>

<!ELEMENT resultado (vencedor, tiempo)>
<!ELEMENT vencedor (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>

<!ELEMENT clasificacion (piloto1, piloto2, piloto3)>
<!ELEMENT piloto1 (#PCDATA)>
<!ELEMENT piloto2 (#PCDATA)>
<!ELEMENT piloto3 (#PCDATA)>

=== uo294254/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<circuito>

    <nombre>Circuito de Jerez – Ángel Nieto</nombre>
    <longitud unidades = "metros">4423</longitud>
    <anchura unidades = "metros">11</anchura>
    <fecha>2025-04-27</fecha>
    <hora>14:00:00</hora>
    <vueltas>25</vueltas>
    <localidad>Jerez de la frontera</localidad>
    <pais>España</pais>
    <patrocinador>Estrella Galicia</patrocinador>

    <referencias>
        <referencia>https://es.wikipedia.org/wiki/Circuito_de_Jerez</referencia>
        <referencia>https://www.motogp.com/es/circuitos/jerez</referencia>
        <referencia>https://www.formula1.com</referencia>
    </referencias>

    <fotos>
        <foto archivo="Panorama.jpg">Vista aérea del circuito</foto>
        <foto archivo="RectaMeta.jpg">Recta de meta</foto>
        <foto archivo="CurvaNieto.jpg">Curva Ángel Nieto</foto>
    </fotos>

    <videos>
        <video archivo="VueltaRapida.mp4">Vuelta rápida a bordo</video>
        <video archivo="Presentacion.mp4">Presentación del circuito</video>
    </videos>

    <punto_origen>
        <longitud_geo>-6.032492698310349</longitud_geo>
        <latitud_geo>36.70967372059718</latitud_geo>
        <altitud_geo>39.0663918688527</altitud_geo>
    </punto_origen>

    <tramos>
        <tramo>
            <distancia unidades="metros">330</distancia>
            <longitud_geo>-6.033901190294554</longitud_geo>
            <latitud_geo>36.71244984817293</latitud_geo>
            <altitud_geo>45.16377878698994</altitud_geo>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">25</distancia>
            <longitud_geo>-6.033811503166589</longitud_geo>
            <latitud_geo>36.71263187443232</latitud_geo>
            <altitud_geo>45.71401320626065</altitud_geo>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">25</distancia>
            <longitud_geo>-6.033602561281616</longitud_geo>
            <latitud_geo>36.71273957149641</latitud_geo>
            <altitud_geo>46.51817923263169</altitud_geo>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">200</distancia>
            <longitud_geo>-6.031392598503689</longitud_geo>
            <latitud_geo>36.71275249940201</latitud_geo>
            <altitud_geo>48.38442696251465</altitud_geo>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">25</distancia>
            <longitud_geo>-6.031212942592031</longitud_geo>
            <latitud_geo>36.71264095216015</latitud_geo>
            <altitud_geo>48.45865435901233</altitud_geo>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">25</distancia>
            <longitud_geo>-6.031157644581491</longitud_geo>
            <latitud_geo>36.71245580610585</latitud_geo>
            <altitud_geo>48.39312980872933</altitud_geo>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">25</distancia>
            <longitud_geo>-6.03132408472354</longitud_geo>
            <latitud_geo>36.71227800939405</latitud_geo>
            <altitud_geo>47.17784964813864</altitud_geo>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">25</distancia>
            <longitud_geo>-6.031880531951784</longitud_geo>
            <latitud_geo>36.71195730020057</latitud_geo>
            <altitud_geo>45.41356013539985</altitud_geo>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">50</distancia>
            <longitud_geo>-6.032092320611424</longitud_geo>
            <latitud_geo>36.71164439543061</latitud_geo>
            <altitud_geo>43.56210950893393</altitud_geo>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">30</distancia>
            <longitud_geo>-6.03201682834019</longitud_geo>
            <latitud_geo>36.71024779018552</latitud_geo>
            <altitud_geo>40.59796097579625</altitud_geo>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">150</distancia>
            <longitud_geo>-6.031724880659739</longitud_geo>
            <latitud_geo>36.70977061061665</latitud_geo>
            <altitud_geo>40.91541216756563</altitud_geo>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">40</distancia>
            <longitud_geo>-6.031072103220117</longitud_geo>
            <latitud_geo>36.70946608403563</latitud_geo>
            <altitud_geo>42.44457601715511</altitud_geo>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">50</distancia>
            <longitud_geo>-6.027856013767456</longitud_geo>
            <latitud_geo>36.70908742945934</latitud_geo>
            <altitud_geo>47.05280412015408</altitud_geo>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">200</distancia>
            <longitud_geo>-6.027387780263576</longitud_geo>
            <latitud_geo>36.70880514406645</latitud_geo>
            <altitud_geo>49.42035729041437</altitud_geo>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">40</distancia>
            <longitud_geo>-6.027188930797433</longitud_geo>
            <latitud_geo>36.70840471475276</latitud_geo>
            <altitud_geo>51.3852681945378</altitud_geo>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">35</distancia>
            <longitud_geo>-6.027261258863938</longitud_geo>
            <latitud_geo>36.7079833397238</latitud_geo>
            <altitud_geo>53.00661157494977</altitud_geo>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">35</distancia>
            <longitud_geo>-6.02752153513949</longitud_geo>
            <latitud_geo>36.70762123284415</latitud_geo>
            <altitud_geo>53.41887889093366</altitud_geo>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">35</distancia>
            <longitud_geo>-6.032887621985132</longitud_geo>
            <latitud_geo>36.70414889985449</latitud_geo>
            <altitud_geo>46.57839673935054</altitud_geo>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">600</distancia>
            <longitud_geo>-6.033172392766527</longitud_geo>
            <latitud_geo>36.7041204698988</latitud_geo>
            <altitud_geo>46.58900608599204</altitud_geo>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">30</distancia>
            <longitud_geo>-6.033374221980359</longitud_geo>
            <latitud_geo>36.7042762163754</latitud_geo>
            <altitud_geo>46.42121581502786</altitud_geo>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">40</distancia>
            <longitud_geo>-6.03338814746964</longitud_geo>
            <latitud_geo>36.70449358039833</latitud_geo>
            <altitud_geo>46.42117336991732</altitud_geo>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">30</distancia>
            <longitud_geo>-6.032392765120146</longitud_geo>
            <latitud_geo>36.70612531086015</latitud_geo>
            <altitud_geo>43.26635776314464</altitud_geo>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">45</distancia>
            <longitud_geo>-6.032477932896767</longitud_geo>
            <latitud_geo>36.70670512537629</latitud_geo>
            <altitud_geo>40.60943949514559</altitud_geo>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">200</distancia>
            <longitud_geo>-6.033893944251218</longitud_geo>
            <latitud_geo>36.7081728175482</latitud_geo>
            <altitud_geo>35.5791065234919</altitud_geo>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">50</distancia>
            <longitud_geo>-6.034421390203213</longitud_geo>
            <latitud_geo>36.70838768337774</latitud_geo>
            <altitud_geo>36.23630127742329</altitud_geo>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">100</distancia>
            <longitud_geo>-6.035056287394483</longitud_geo>
            <latitud_geo>36.70827909719887</latitud_geo>
            <altitud_geo>36.26304470178065</altitud_geo>
            <sector>4</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">35</distancia>
            <longitud_geo>-6.035567921880991</longitud_geo>
            <latitud_geo>36.70792653147418</latitud_geo>
            <altitud_geo>36.69337027476826</altitud_geo>
            <sector>4</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">130</distancia>
            <longitud_geo>-6.036387313072229</longitud_geo>
            <latitud_geo>36.70615718474786</latitud_geo>
            <altitud_geo>39.39320633968551</altitud_geo>
            <sector>4</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">45</distancia>
            <longitud_geo>-6.03690093483409</longitud_geo>
            <latitud_geo>36.70601030837597</latitud_geo>
